# Generated by Django 6.1.1 on 2026-09-07 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('ip', models.CharField(max_length=50, verbose_name='IP')),
                ('protocol', models.CharField(choices=[('modbus', 'Modbus TCP'), ('opcua', 'OPC UA'), ('s7', 'Siemens S7')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название правила')),
                ('condition', models.TextField(default="tags.get('pressure', 99) < 2.0", verbose_name='Условие (Python)')),
                ('action', models.TextField(default="stop('pump_01')", verbose_name='Действие')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('layout', models.JSONField(default=dict, verbose_name='JSON layout конструктора')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тэг (temp_01)')),
                ('address', models.IntegerField(verbose_name='Адрес регистра')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Ед. изм.')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scada.device')),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('number', 'Число'), ('chart', 'График'), ('indicator', 'Индикатор')], default='number', max_length=20)),
                ('row', models.IntegerField(default=0)),
                ('col', models.IntegerField(default=0)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='scada.screen')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scada.tag')),
            ],
        ),
    ]
