# Generated by Django 6.1.1 on 2026-09-11 04:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0003_servicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='screen',
            name='height',
            field=models.IntegerField(default=600, verbose_name='Высота канваса'),
        ),
        migrations.AddField(
            model_name='screen',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='screen',
            name='widgets',
            field=models.JSONField(default=list, verbose_name='Виджеты (JSON)'),
        ),
        migrations.AddField(
            model_name='screen',
            name='width',
            field=models.IntegerField(default=900, verbose_name='Ширина канваса'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='layout',
            field=models.JSONField(default=dict, verbose_name='JSON layout конструктора (legacy)'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_widgets', to='scada.screen'),
        ),
    ]
