# Generated by Django 6.1.1 on 2026-09-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0004_screen_created_at_screen_height_screen_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='layout',
            field=models.JSONField(blank=True, default=dict, verbose_name='JSON layout конструктора (legacy)'),
        ),
    ]
