# Generated by Django 6.1.1 on 2026-09-08 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scada', '0003_servicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('temperature', 'Температура'), ('pressure', 'Давление'), ('digital_input', 'Дискретный вход'), ('motor', 'Двигатель')], max_length=20, verbose_name='Тип сигнала')),
                ('mode', models.CharField(choices=[('constant', 'Постоянное'), ('random', 'Случайное'), ('sine', 'Синусоида'), ('ramp', 'Пила (ramp)'), ('cycle', 'Цикл 0/1 (cycle)')], max_length=20, verbose_name='Режим генерации')),
                ('min_value', models.FloatField(verbose_name='Минимум диапазона')),
                ('max_value', models.FloatField(verbose_name='Максимум диапазона')),
                ('period', models.FloatField(default=60, help_text='Для constant/random не используется.', verbose_name='Период, сек (sine/ramp/cycle)')),
                ('update_interval', models.FloatField(verbose_name='Интервал генерации, сек')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включён')),
                ('device', models.ForeignKey(help_text='Показания какого устройства эмулируются. Источник правды для карты регистров.', on_delete=django.db.models.deletion.CASCADE, related_name='simulators', to='scada.device', verbose_name='Реальное устройство')),
                ('tag', models.ForeignKey(help_text='В какой тэг публиковать (ключ в latest_tags = tag.name).', on_delete=django.db.models.deletion.CASCADE, related_name='simulators', to='scada.tag', verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Симулятор',
                'verbose_name_plural': 'Симуляторы',
            },
        ),
    ]
